import { afterEach, expect, it } from "vitest";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { mkdtemp, mkdir, readFile, realpath, rm, writeFile, access } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createCommandContext } from "../test-helpers.js";
import { VaultFS } from "../lib/vault-fs.js";
import { resolveWorkspaceContext } from "../lib/workspace-context.js";
import { invalidateProjectMapCache } from "../lib/project-detector.js";
import { graphTraverseCommand } from "./graph.js";
import { sessionCommand } from "./session.js";
import { activateSkills, compactActivationResult } from "./skill/activate.js";

const exec = promisify(execFile);
const env = { ...process.env, GIT_AUTHOR_NAME: "Test", GIT_AUTHOR_EMAIL: "test@example.com", GIT_COMMITTER_NAME: "Test", GIT_COMMITTER_EMAIL: "test@example.com", GIT_CONFIG_GLOBAL: "/dev/null", GIT_CONFIG_NOSYSTEM: "1" };
const git = async (cwd: string, args: string[]) => (await exec("git", args, { cwd, env })).stdout;
let root: string | undefined;
afterEach(async () => { invalidateProjectMapCache(); if (root) await rm(root, { recursive: true, force: true }); });

it("initializes and routes a linked workspace then cleans it after completion and main integration", async () => {
  root = await realpath(await mkdtemp(join(tmpdir(), "superskill-lifecycle-e2e-")));
  const repo = join(root, "repo");
  const tree = join(root, "worker-checkout");
  const vault = join(root, "vault");
  await mkdir(repo);
  await mkdir(vault);
  await git(repo, ["init", "-qb", "main"]);
  await writeFile(join(repo, ".gitignore"), ".superskill/\n");
  await writeFile(join(repo, "package.json"), '{"name":"fixture","type":"module"}');
  await writeFile(join(repo, "worker.py"), "print('base')\n");
  await git(repo, ["add", "."]);
  await git(repo, ["commit", "-qm", "base"]);
  await git(repo, ["worktree", "add", "-qb", "worker", tree]);
  await writeFile(join(vault, "project-map.json"), JSON.stringify({ [repo]: "fixture" }));
  invalidateProjectMapCache();
  const resolved = await resolveWorkspaceContext(vault, tree, "fixture");
  const ctx = createCommandContext(new VaultFS(vault), resolved);
  const start = await sessionCommand({ action: "register", tool: "codex", project: "fixture" }, ctx);
  expect(start.worktree?.currentLinked).toBe(true);
  const activation = await activateSkills({ task: "implement worker", files: ["worker.py"], phase: "implement", session_id: start.session_id, max_tokens: 4000 }, ctx);
  expect(activation.success).toBe(true);
  expect(activation.initialization?.success).toBe(true);
  expect(activation.matched_skill_ids).toContain("code/python");
  expect(compactActivationResult(activation).worktree?.workspacePath).toBe(tree);
  expect(await graphTraverseCommand({ action: "open", id: "code:worker.py" }, ctx)).toMatchObject({ content: "print('base')\n" });
  await writeFile(join(tree, "worker.py"), "print('done')\n");
  await git(tree, ["commit", "-qam", "work"]);
  const mainCtx = { ...ctx, workspacePath: repo };
  const done = await sessionCommand({ action: "complete", sessionId: start.session_id, project: "fixture", outcome: "done" }, mainCtx);
  expect(done.worktree?.cleanup?.removed).toEqual([]);
  expect(done.worktree?.cleanup?.kept.some(item => item.path === tree)).toBe(true);
  const graph = JSON.parse(await readFile(join(tree, ".superskill", "graph.json"), "utf8"));
  expect(graph.nodes.find((node: { coordinationSessionId?: string }) => node.coordinationSessionId === start.session_id).outcome).toBe("success");
  await git(repo, ["merge", "--ff-only", "worker"]);
  const next = await sessionCommand({ action: "register", tool: "codex", project: "fixture" }, mainCtx);
  expect(next.worktree?.cleanup?.removed).toEqual([tree]);
  expect(next.worktree?.cleanup?.archives).toHaveLength(1);
  await expect(access(tree)).rejects.toThrow();
  expect(await readFile(join(next.worktree!.cleanup!.archives![0].path, "graph.json"), "utf8")).toContain(start.session_id!);
  expect((await ctx.sessionRegistry.get(start.session_id!))?.workspace_path).toBeUndefined();
}, 30000);
