// SPDX-License-Identifier: Apache-2.0
import type { ClientConfig } from "./types.js";

function home(sub: string): Record<"darwin" | "linux" | "win32", string> {
  return { darwin: `~/${sub}`, linux: `~/${sub}`, win32: `~/${sub}` };
}

export const CLIENT_REGISTRY: ClientConfig[] = [
  {
    name: "Claude Code",
    slug: "claude-code",
    mcpConfigPaths: home(".claude.json"),
    configFormat: "json",
    rootKey: "mcpServers",
    commandType: "string",
    envKey: "env",
    instructionStrategy: "markdown-file",
    instructionPaths: home(".claude/CLAUDE.md"),
    commandPaths: home(".claude/commands"),
    support: "documented",
  },
  {
    name: "Claude Desktop",
    slug: "claude-desktop",
    mcpConfigPaths: {
      darwin: "~/Library/Application Support/Claude/claude_desktop_config.json",
      linux: "~/.config/Claude/claude_desktop_config.json",
      win32: "~/AppData/Roaming/Claude/claude_desktop_config.json",
    },
    configFormat: "json",
    rootKey: "mcpServers",
    commandType: "string",
    envKey: "env",
    instructionStrategy: "none",
    support: "documented",
  },
  {
    name: "Cursor",
    slug: "cursor",
    mcpConfigPaths: home(".cursor/mcp.json"),
    configFormat: "json",
    rootKey: "mcpServers",
    commandType: "string",
    envKey: "env",
    instructionStrategy: "mdc-file",
    instructionPaths: home(".cursor/rules/superskill.mdc"),
    commandPaths: home(".cursor/commands"),
    support: "documented",
  },
  {
    name: "OpenCode",
    slug: "opencode",
    mcpConfigPaths: home(".config/opencode/opencode.json"),
    configFormat: "json",
    rootKey: "mcp",
    commandType: "array",
    envKey: "environment",
    extraFields: { type: "local" },
    instructionStrategy: "config-array",
    instructionPaths: home(".config/opencode/superskill-instructions.md"),
    commandPaths: home(".config/opencode/commands"),
    support: "documented",
  },
  {
    name: "Crush CLI",
    slug: "crush",
    mcpConfigPaths: {
      darwin: "~/.config/crush/crush.json",
      linux: "~/.config/crush/crush.json",
      win32: "~/AppData/Local/crush/crush.json",
    },
    configFormat: "json",
    rootKey: "mcp",
    commandType: "string",
    envKey: "env",
    extraFields: { type: "stdio" },
    instructionStrategy: "none",
    support: "documented",
  },
  {
    name: "Codex CLI",
    slug: "codex",
    mcpConfigPaths: home(".codex/config.toml"),
    configFormat: "toml",
    rootKey: "mcp_servers",
    commandType: "string",
    envKey: "env",
    instructionStrategy: "markdown-file",
    instructionPaths: home(".codex/AGENTS.md"),
    commandPaths: home(".codex/prompts"),
    support: "documented",
  },
  {
    name: "Gemini CLI",
    slug: "gemini",
    mcpConfigPaths: home(".gemini/settings.json"),
    configFormat: "json",
    rootKey: "mcpServers",
    commandType: "string",
    envKey: "env",
    instructionStrategy: "markdown-file",
    instructionPaths: home(".gemini/GEMINI.md"),
    commandPaths: home(".gemini/commands"),
    support: "documented",
  },
  {
    name: "Droid",
    slug: "droid",
    mcpConfigPaths: home(".factory/mcp.json"),
    configFormat: "json",
    rootKey: "mcpServers",
    commandType: "string",
    envKey: "env",
    instructionStrategy: "markdown-file",
    instructionPaths: home(".factory/AGENTS.md"),
    support: "documented",
  },
  {
    name: "Windsurf",
    slug: "windsurf",
    supportNote: "Targets legacy Windsurf installations. Devin Desktop uses a different config location; consult docs/harness.md.",
    mcpConfigPaths: home(".codeium/windsurf/mcp_config.json"),
    configFormat: "json",
    rootKey: "mcpServers",
    commandType: "string",
    envKey: "env",
    instructionStrategy: "markdown-file",
    instructionPaths: home(".codeium/windsurf/memories/global_rules.md"),
    support: "documented",
  },
  {
    name: "Aider",
    slug: "aider",
    supportNote: "Native MCP setup is unsupported. Use superskill-cli graph resolve <task> and superskill-cli graph open <id>, then supply the selected output to Aider.",
    mcpConfigPaths: home(".aider/mcp.json"),
    configFormat: "json",
    rootKey: "mcpServers",
    commandType: "string",
    envKey: "env",
    instructionStrategy: "none",
    support: "unsupported",
  },
  {
    name: "Continue IDE",
    slug: "continue",
    detectionPaths: home(".continue"),
    supportNote: "Configures the Continue IDE extension. Continue CLI requires its config.yaml MCP configuration; this setup does not configure cn.",
    mcpConfigPaths: home(".continue/mcpServers/superskill.json"),
    configFormat: "json",
    rootKey: "mcpServers",
    commandType: "string",
    envKey: "env",
    instructionStrategy: "none",
    support: "documented",
  },
];
