// SPDX-License-Identifier: AGPL-3.0-or-later OR Commercial
import type { ClientConfig } from "./types.js";

function home(sub: string): Record<"darwin" | "linux" | "win32", string> {
  return { darwin: `~/${sub}`, linux: `~/${sub}`, win32: `~/${sub}` };
}

export const CLIENT_REGISTRY: ClientConfig[] = [
  {
    name: "Claude Code",
    slug: "claude-code",
    mcpConfigPaths: home(".claude.json"),
    configFormat: "json",
    rootKey: "mcpServers",
    commandType: "string",
    envKey: "env",
    instructionStrategy: "markdown-file",
    instructionPaths: home(".claude/CLAUDE.md"),
    verified: true,
  },
  {
    name: "Claude Desktop",
    slug: "claude-desktop",
    mcpConfigPaths: {
      darwin: "~/Library/Application Support/Claude/claude_desktop_config.json",
      linux: "~/.config/Claude/claude_desktop_config.json",
      win32: "~/AppData/Roaming/Claude/claude_desktop_config.json",
    },
    configFormat: "json",
    rootKey: "mcpServers",
    commandType: "string",
    envKey: "env",
    instructionStrategy: "none",
    verified: true,
  },
  {
    name: "Cursor",
    slug: "cursor",
    mcpConfigPaths: home(".cursor/mcp.json"),
    configFormat: "json",
    rootKey: "mcpServers",
    commandType: "string",
    envKey: "env",
    instructionStrategy: "mdc-file",
    instructionPaths: home(".cursor/rules/superskill.mdc"),
    verified: true,
  },
  {
    name: "OpenCode",
    slug: "opencode",
    mcpConfigPaths: home(".config/opencode/opencode.json"),
    configFormat: "json",
    rootKey: "mcp",
    commandType: "array",
    envKey: "environment",
    extraFields: { type: "local" },
    instructionStrategy: "config-array",
    instructionPaths: home(".config/opencode/superskill-instructions.md"),
    verified: false,
  },
  {
    name: "Crush CLI",
    slug: "crush",
    mcpConfigPaths: {
      darwin: "~/.config/crush/crush.json",
      linux: "~/.config/crush/crush.json",
      win32: "~/AppData/Local/crush/crush.json",
    },
    configFormat: "json",
    rootKey: "mcp",
    commandType: "string",
    envKey: "env",
    instructionStrategy: "none",
    verified: false,
  },
  {
    name: "Codex CLI",
    slug: "codex",
    mcpConfigPaths: home(".codex/config.toml"),
    configFormat: "toml",
    rootKey: "mcp_servers",
    commandType: "string",
    envKey: "env",
    instructionStrategy: "markdown-file",
    instructionPaths: home(".codex/AGENTS.md"),
    verified: true,
  },
  {
    name: "Gemini CLI",
    slug: "gemini",
    mcpConfigPaths: home(".gemini/settings.json"),
    configFormat: "json",
    rootKey: "mcpServers",
    commandType: "string",
    envKey: "env",
    instructionStrategy: "markdown-file",
    instructionPaths: home(".gemini/GEMINI.md"),
    verified: true,
  },
  {
    name: "Droid",
    slug: "droid",
    mcpConfigPaths: home(".factory/mcp.json"),
    configFormat: "json",
    rootKey: "mcpServers",
    commandType: "string",
    envKey: "env",
    instructionStrategy: "markdown-file",
    instructionPaths: home(".factory/CLAUDE.md"),
    verified: false,
  },
];
